vm:
  box: 'centos/7'
  osVersion: 7  
  #box: 'centos/6'
  #osVersion: 6 
  proxyExists: 'true'
  proxyException: '*'
  infrastructure: 'HOME'
  domainName: '.bumblebee.local'
  bridgeNetworkAdapter: 'en0: Wi-Fi (AirPort)'
  bootstrapperHome: '/home/vagrant/vagrant-prov' 
  workspace:
    name: 'workspace'
    env: 'envx'
    internalip: '192.168.100.101'
    memory: '2048'
  master:
    name: 'kmaster'
    env: 'envx'
    internalip: '192.168.100.210'
    memory: '512'    
  worker:
    numOfNodes: 1
    env: 'envx'
    internalbaseip: '192.168.100.20'
    prefixName: 'kworker0'
    suffixName: 'lx'
    memory: '512'